### ISSUE TITLE
404になる

### ISSUE THREAD

**Issue by Ryoga-exe** [kss-pc-club/typing#7]
少し前から、 https://typing.kss-pc.club にアクセスすると404エラーになります。

恐らく、何らかの設定が原因だと思うので修正お願いします。

**Comment by a01sa01to** [comment]
ブランチ名を変えたときに、GitHub Pagesの設定がリセットされたのが原因のようです。
この問題は解決し、アクセスできるようになりました。報告ありがとうございました。
